### ISSUE TITLE
Should we just merge with vcsh?

### ISSUE THREAD

**Issue by RadicalZephyr** [RadicalZephyr/hermit#64]
Hermit is cool and it's been a fun project, but it seems like [`vcsh`](https://github.com/RichiH/vcsh) is an even cooler take on the same basic issue.

We might be able to add a more interesting and robust profiles feature to `vcsh` and adding redaction shouldn't be that hard either...

What do you think @reillysiemens?

**Comment by reillysiemens** [comment]
Did we ever reach a conclusion on this? I like the modularity of only cloning the config files you need, but I also don't like the idea of managing a different repo for `ssh`, `zsh`, and `vim`... My dotfiles are, for me, a productivity library. I rarely just want one component of them. If I do I'll just `scp` one file where I need it.

**Comment by RadicalZephyr** [comment]
I say we keep working on hermit.  It wouldn't do to just abandon our pet project to die...

**Comment by reillysiemens** [comment]
Word. I think this was the right choice. :smile:
