### ISSUE TITLE
hermit status reports incorrect profile when no profile exists

### ISSUE THREAD

**Issue by reillysiemens** [RadicalZephyr/hermit#67]
Currently if you have just installed hermit and you run a `hermit status` it reports the following:
```
Current profile: default
Located at: /home/user/.hermit/profiles/default
```
That location doesn't exist if you haven't run hermit init first. `hermit status` should actually check to see if the profile exists before reporting its status. A more appropriate message might be something like:
```
No profile to report on. Run `hermit init' to create a profile.
```

**Comment by RadicalZephyr** [comment]
Yeah, the profile code is pretty buggy I think.  I don't think use actually works correctly, and there are all sorts of unconsidered use cases.
