### ISSUE TITLE
hermit init incorrectly reports profile location

### ISSUE THREAD

**Issue by reillysiemens** [RadicalZephyr/hermit#68]
When you first run `hermit init` the last line of output is
```
Congratulations! You now have a brand new hermit located at <name of profile>.
```
Hermit should instead report the profile location.

**Comment by houngj** [comment]
Line 56 at `.hermit/lib/hermit-init` needs to reference `$HERMIT_PROFILE_PATH` instead of `$HERMIT_PROFILE`.
