### ISSUE TITLE
hermit use initializes a repository

### ISSUE THREAD

**Issue by reillysiemens** [RadicalZephyr/hermit#69]
If I have two profiles (say foobar and default) and I wish to remove one of them (say foobar) I might go into `~/.hermit/profiles` and run `rm -rf foobar`. If I then go to run `hermit use default` to switch over to the default profile I get something like the following:
```
Your profile hasn't been initialized yet, try running Initialized empty Git repository in /home/user/.hermit/profiles/foobar/.git/
[master (root-commit) 1c9ba9e] Initial commit
 1 file changed, 1 insertion(+)
 create mode 100644 .gitignore
Congratulations! You now have a brand new hermit located at foobar.

```
and voila! I have a brand new foobar when I didn't want one at all.

I'm fairly certain this is because
```
[hermit]
        current = foobar
```
is still set in `~/.hermit/.git/config`. Does hermit need a `hermit remove` command?

**Comment by RadicalZephyr** [comment]
Okay, clearly the current behaviour is wrong.  But I'm not 100% clear on what the right behaviour is.

I think I need some use cases.
